export const TIPOS_ENTIDADE = [
  { id: "canteiro",
    nome: "Canteiro",
    tagVariant: "warning",
    desenhavel: true,
    monitoravel: true,
    manejavel: true,
    inspecionavel: true,
  },
  { id: "planta",
    nome: "Planta",
    tagVariant: "success",
    desenhavel: false,
    monitoravel: true,
    manejavel: true,
    inspecionavel: true,
  },
  { id: "horta",
    nome: "Horta",
    tagVariant: "primary",
    desenhavel: false,
    monitoravel: true,
    manejavel: false,
    inspecionavel: false,
  },
];
